trigger:
- main
variables:
    # Container registry service connection established during pipeline creation
    # dockerRegistryServiceConnection: '{{ containerRegistryConnection.Id }}'
    # imageRepository: 'test'
    # containerRegistry: 'kunmipipelinetest.azurecr.io'
    # dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
    tag: '$(Build.BuildId)'
pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world! Can you see this?
  displayName: 'Run a one-line script'
- task: Docker@2 
  displayName: Build and push an image to container registry
  inputs:
    containerRegistry: 'kunmipipelinetest'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/test/Dockerfile'
    tags: '$(tag)'
    addPipelineData: false
     
