trigger:
- main
variables:
    # Container registry service connection established during pipeline creation
    # dockerRegistryServiceConnection: '{{ containerRegistryConnection.Id }}'
    # imageRepository: 'test'
    # containerRegistry: 'kunmipipelinetest.azurecr.io'
    # dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
    azureSubscription: 'tochipipelinetest'
    tag: '$(Build.BuildId)'
pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world! Can you see this?
  displayName: 'Run a one-line script'
- task: Docker@2 
  displayName: Build and push an image to container registry
  inputs:
    containerRegistry: 'kunmipipelinetest'
    repository: 'testing'
    command: 'buildAndPush'
    Dockerfile: '**/test/Dockerfile'
    tags: '$(tag)'
    addPipelineData: false

- task: Kubernetes@1
  displayName: 'Deploy to Kubernetes'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: '$(azureSubscription)'
    azureResourceGroup: 'pipelinetest'
    kubernetesCluster: 'akspipelinecluster'
    namespace: 'default'
    command: 'apply'
    arguments: '-f ./deployment.yml'
    secretType: 'dockerRegistry'
    dockerRegistryEndpoint: 'kunmipipelinetest.azurecr.io'
    dockerRegistryServiceConnection: 'kunmipipelinetest'
    containerRegistryType: 'Azure Container Registry'
    dockerRegistryServiceConnectionSecretName: 'acrsecret'
